// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace JedinicnoTestiranje
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinTitleBar uIPIAplikacijazaSkladiTitleBar = this.UIPIAplikacijazaSkladiWindow.UIPIAplikacijazaSkladiTitleBar;
            WinWindow uIPIAplikacijazaSkladiWindow = this.UIPIAplikacijazaSkladiWindow;
            WinMenuItem uIArtikliMenuItem = this.UIPIAplikacijazaSkladiWindow.UIMnuMeniMenuBar.UIArtikliMenuItem;
            WinMenuItem uIPrijamnicaMenuItem = this.UIPIAplikacijazaSkladiWindow.UIMnuMeniMenuBar.UIDokumentiMenuItem.UIUnosMenuItem.UIPrijamnicaMenuItem;
            WinComboBox uICBDobavljacComboBox = this.UIPIAplikacijazaSkladiWindow.UIUnosprijemniceWindow.UICBDobavljacWindow.UICBDobavljacComboBox;
            WinComboBox uIOdabirArtiklaComboBox = this.UIPIAplikacijazaSkladiWindow.UIUnosprijemniceWindow.UICBArtiklWindow.UIOdabirArtiklaComboBox;
            WinEdit uITxtKolicinaEdit = this.UIPIAplikacijazaSkladiWindow.UIUnosprijemniceWindow.UITxtKolicinaWindow.UITxtKolicinaEdit;
            WinButton uIDodajStavkuButton = this.UIPIAplikacijazaSkladiWindow.UIUnosprijemniceWindow.UIDodajStavkuWindow.UIDodajStavkuButton;
            WinButton uIUnesiButton = this.UIPIAplikacijazaSkladiWindow.UIUnosprijemniceWindow.UIUnesiWindow.UIUnesiButton;
            #endregion

            // Last mouse action was not recorded.

            // Click 'PI Aplikacija za Skladište' title bar
            Mouse.Click(uIPIAplikacijazaSkladiTitleBar, new Point(78, 5));

            // Maximize window 'PI Aplikacija za Skladište'
            uIPIAplikacijazaSkladiWindow.Maximized = this.RecordedMethod1Params.UIPIAplikacijazaSkladiWindowMaximized;

            // Click 'Artikli' menu item
            Mouse.Click(uIArtikliMenuItem, new Point(26, 8));

            // Click 'Dokumenti' -> 'Unos' -> 'Prijamnica' menu item
            Mouse.Click(uIPrijamnicaMenuItem, new Point(35, 11));

            // Select 'Lins' in 'CBDobavljac' combo box
            uICBDobavljacComboBox.SelectedItem = this.RecordedMethod1Params.UICBDobavljacComboBoxSelectedItem;

            // Select 'Koaksijalni kabel' in 'Odabir Artikla' combo box
            uIOdabirArtiklaComboBox.SelectedItem = this.RecordedMethod1Params.UIOdabirArtiklaComboBoxSelectedItem;

            // Type '12' in 'txtKolicina' text box
            uITxtKolicinaEdit.Text = this.RecordedMethod1Params.UITxtKolicinaEditText;

            // Click 'Dodaj Stavku' button
            Mouse.Click(uIDodajStavkuButton, new Point(49, 20));

            // Click 'Unesi' button
            Mouse.Click(uIUnesiButton, new Point(48, 11));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIPIAplikacijazaSkladiWindow UIPIAplikacijazaSkladiWindow
        {
            get
            {
                if ((this.mUIPIAplikacijazaSkladiWindow == null))
                {
                    this.mUIPIAplikacijazaSkladiWindow = new UIPIAplikacijazaSkladiWindow();
                }
                return this.mUIPIAplikacijazaSkladiWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIPIAplikacijazaSkladiWindow mUIPIAplikacijazaSkladiWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Maximize window 'PI Aplikacija za Skladište'
        /// </summary>
        public bool UIPIAplikacijazaSkladiWindowMaximized = true;
        
        /// <summary>
        /// Select 'Lins' in 'CBDobavljac' combo box
        /// </summary>
        public string UICBDobavljacComboBoxSelectedItem = "Lins";
        
        /// <summary>
        /// Select 'Koaksijalni kabel' in 'Odabir Artikla' combo box
        /// </summary>
        public string UIOdabirArtiklaComboBoxSelectedItem = "Koaksijalni kabel";
        
        /// <summary>
        /// Type '12' in 'txtKolicina' text box
        /// </summary>
        public string UITxtKolicinaEditText = "12";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPIAplikacijazaSkladiWindow : WinWindow
    {
        
        public UIPIAplikacijazaSkladiWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "PI Aplikacija za Skladište";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UIPIAplikacijazaSkladiTitleBar
        {
            get
            {
                if ((this.mUIPIAplikacijazaSkladiTitleBar == null))
                {
                    this.mUIPIAplikacijazaSkladiTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUIPIAplikacijazaSkladiTitleBar.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUIPIAplikacijazaSkladiTitleBar;
            }
        }
        
        public UIMnuMeniMenuBar UIMnuMeniMenuBar
        {
            get
            {
                if ((this.mUIMnuMeniMenuBar == null))
                {
                    this.mUIMnuMeniMenuBar = new UIMnuMeniMenuBar(this);
                }
                return this.mUIMnuMeniMenuBar;
            }
        }
        
        public UIUnosprijemniceWindow UIUnosprijemniceWindow
        {
            get
            {
                if ((this.mUIUnosprijemniceWindow == null))
                {
                    this.mUIUnosprijemniceWindow = new UIUnosprijemniceWindow(this);
                }
                return this.mUIUnosprijemniceWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUIPIAplikacijazaSkladiTitleBar;
        
        private UIMnuMeniMenuBar mUIMnuMeniMenuBar;
        
        private UIUnosprijemniceWindow mUIUnosprijemniceWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMnuMeniMenuBar : WinMenuBar
    {
        
        public UIMnuMeniMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIArtikliMenuItem
        {
            get
            {
                if ((this.mUIArtikliMenuItem == null))
                {
                    this.mUIArtikliMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIArtikliMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Artikli";
                    this.mUIArtikliMenuItem.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUIArtikliMenuItem;
            }
        }
        
        public UIDokumentiMenuItem UIDokumentiMenuItem
        {
            get
            {
                if ((this.mUIDokumentiMenuItem == null))
                {
                    this.mUIDokumentiMenuItem = new UIDokumentiMenuItem(this);
                }
                return this.mUIDokumentiMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIArtikliMenuItem;
        
        private UIDokumentiMenuItem mUIDokumentiMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDokumentiMenuItem : WinMenuItem
    {
        
        public UIDokumentiMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Dokumenti";
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public UIUnosMenuItem UIUnosMenuItem
        {
            get
            {
                if ((this.mUIUnosMenuItem == null))
                {
                    this.mUIUnosMenuItem = new UIUnosMenuItem(this);
                }
                return this.mUIUnosMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIUnosMenuItem mUIUnosMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIUnosMenuItem : WinMenuItem
    {
        
        public UIUnosMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Unos";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIPrijamnicaMenuItem
        {
            get
            {
                if ((this.mUIPrijamnicaMenuItem == null))
                {
                    this.mUIPrijamnicaMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIPrijamnicaMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Prijamnica";
                    this.mUIPrijamnicaMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIPrijamnicaMenuItem.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUIPrijamnicaMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIPrijamnicaMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIUnosprijemniceWindow : WinWindow
    {
        
        public UIUnosprijemniceWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "frmUnosPrijamnice";
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public UICBDobavljacWindow UICBDobavljacWindow
        {
            get
            {
                if ((this.mUICBDobavljacWindow == null))
                {
                    this.mUICBDobavljacWindow = new UICBDobavljacWindow(this);
                }
                return this.mUICBDobavljacWindow;
            }
        }
        
        public UICBArtiklWindow UICBArtiklWindow
        {
            get
            {
                if ((this.mUICBArtiklWindow == null))
                {
                    this.mUICBArtiklWindow = new UICBArtiklWindow(this);
                }
                return this.mUICBArtiklWindow;
            }
        }
        
        public UITxtKolicinaWindow UITxtKolicinaWindow
        {
            get
            {
                if ((this.mUITxtKolicinaWindow == null))
                {
                    this.mUITxtKolicinaWindow = new UITxtKolicinaWindow(this);
                }
                return this.mUITxtKolicinaWindow;
            }
        }
        
        public UIDodajStavkuWindow UIDodajStavkuWindow
        {
            get
            {
                if ((this.mUIDodajStavkuWindow == null))
                {
                    this.mUIDodajStavkuWindow = new UIDodajStavkuWindow(this);
                }
                return this.mUIDodajStavkuWindow;
            }
        }
        
        public UIUnesiWindow UIUnesiWindow
        {
            get
            {
                if ((this.mUIUnesiWindow == null))
                {
                    this.mUIUnesiWindow = new UIUnesiWindow(this);
                }
                return this.mUIUnesiWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICBDobavljacWindow mUICBDobavljacWindow;
        
        private UICBArtiklWindow mUICBArtiklWindow;
        
        private UITxtKolicinaWindow mUITxtKolicinaWindow;
        
        private UIDodajStavkuWindow mUIDodajStavkuWindow;
        
        private UIUnesiWindow mUIUnesiWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICBDobavljacWindow : WinWindow
    {
        
        public UICBDobavljacWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBDobavljac";
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICBDobavljacComboBox
        {
            get
            {
                if ((this.mUICBDobavljacComboBox == null))
                {
                    this.mUICBDobavljacComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICBDobavljacComboBox.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUICBDobavljacComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICBDobavljacComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICBArtiklWindow : WinWindow
    {
        
        public UICBArtiklWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "CBArtikl";
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIOdabirArtiklaComboBox
        {
            get
            {
                if ((this.mUIOdabirArtiklaComboBox == null))
                {
                    this.mUIOdabirArtiklaComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIOdabirArtiklaComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Odabir Artikla";
                    this.mUIOdabirArtiklaComboBox.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUIOdabirArtiklaComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIOdabirArtiklaComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtKolicinaWindow : WinWindow
    {
        
        public UITxtKolicinaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtKolicina";
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtKolicinaEdit
        {
            get
            {
                if ((this.mUITxtKolicinaEdit == null))
                {
                    this.mUITxtKolicinaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtKolicinaEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Kolicina";
                    this.mUITxtKolicinaEdit.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUITxtKolicinaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtKolicinaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDodajStavkuWindow : WinWindow
    {
        
        public UIDodajStavkuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnDodajStavku";
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinButton UIDodajStavkuButton
        {
            get
            {
                if ((this.mUIDodajStavkuButton == null))
                {
                    this.mUIDodajStavkuButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDodajStavkuButton.SearchProperties[WinButton.PropertyNames.Name] = "Dodaj Stavku";
                    this.mUIDodajStavkuButton.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUIDodajStavkuButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDodajStavkuButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIUnesiWindow : WinWindow
    {
        
        public UIUnesiWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnUnesiPrijamnicu";
            this.WindowTitles.Add("PI Aplikacija za Skladište");
            #endregion
        }
        
        #region Properties
        public WinButton UIUnesiButton
        {
            get
            {
                if ((this.mUIUnesiButton == null))
                {
                    this.mUIUnesiButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIUnesiButton.SearchProperties[WinButton.PropertyNames.Name] = "Unesi";
                    this.mUIUnesiButton.WindowTitles.Add("PI Aplikacija za Skladište");
                    #endregion
                }
                return this.mUIUnesiButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIUnesiButton;
        #endregion
    }
}
